### ISSUE TITLE
Column not found: 1054 Unknown column 'two_factor_confirmed_at' in 'field list'

### ISSUE THREAD

**Issue by o-ayoub** [jesusantguerrero/sunday#103]
![demo_](https://user-images.githubusercontent.com/27408905/187073966-4e0d3f8a-f41f-4aec-b52a-7b2bf5774b6d.png)

**Comment by jesusantguerrero** [comment]
In the console run `php artisan migrate`

**Comment by o-ayoub** [comment]
it does not work, I have created a new database, run migrate + seed, the same error !!

**Comment by jesusantguerrero** [comment]
mm did you have the latest changes? because the migration is right there
see the field here:

https://github.com/jesusantguerrero/sunday/blob/master/database/migrations/2022_08_27_183155_update_user.php

verify if you got that file in your local, if not, pull the latest changes from github.

**Comment by o-ayoub** [comment]
Fixed after fresh installation, Thank you
