### ISSUE TITLE
Error run Code

### ISSUE THREAD

**Issue by thanhhff** [jesusantguerrero/sunday#54]
Dear **jesusantguerrero**,
I am trying to run your program but get the following error:

When I run `composer`:
```
[RuntimeException]                                                           
  require.php-mailparse is invalid, it should have a vendor name, a forward s  
  lash, and a package name. The vendor and package name can be words separate  
  d by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*  
  /[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".    
```
I then deleted **"php-mailparse": "*"** from the **composer.json** file.

But when I run **migrations** I get the following error and I don't know how to fix it:
```
   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667▕         // If an exception occurs when attempting to run a query, we'll format the error
    668▕         // message to include the bindings with SQL, which will make this exception a
    669▕         // lot more helpful to the developer instead of just the database's errors.
    670▕         catch (Exception $e) {
  ➜ 671▕             throw new QueryException(
    672▕                 $query, $this->prepareBindings($bindings), $e
    673▕             );
    674▕         }
    675▕ 

      +36 vendor frames 
  37  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
Can you help me run your program? Thank you very much.

**Comment by jesusantguerrero** [comment]
Hello oops I will fix the error with mailparse.

But the migration error seems to be configuration. Makes sure to fill the `.env` file in roots with the correct DB name and password and the database must exist.

let me know if that worked for you.

**Comment by jesusantguerrero** [comment]
Hi thanks for reaching me out about these issues.

I download the code again to fallow the instructions again using docker. Here are the posible solutions.

- In the `.env` file change `DB_HOST` to `DB_HOST=db` (`db` is the name of the mysql service in composer-docker.yml`
- if that doesn't work it it cached so delete the sunday containers and volumes. update the repo with my latest changes and start the process again.

Hope it helps.

**Comment by thanhhff** [comment]
Thank you for replying and fixing bugs running on Docker.
Your website is looking great. 
Have a nice week !
