### ISSUE TITLE
problem installation 

### ISSUE THREAD

**Issue by abelnexus** [jesusantguerrero/sunday#86]
when execute composer install:

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-mailparse * is missing from your system. Install or enable PHP's mailparse extension.
  Problem 2
    - Installation request for php-mime-mail-parser/php-mime-mail-parser 6.0.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[6.0.0].
    - php-mime-mail-parser/php-mime-mail-parser 6.0.0 requires ext-mailparse * -> the requested PHP extension mailparse is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by jesusantguerrero** [comment]
Thank you for opening the issue, I am going to update the readme add this.

With docker those warnings dont show up.

but without docker you have to install ext-mailparse or run `composer install --ignore-platform-reqs`

**Comment by jesusantguerrero** [comment]
Updated the readme for installation steps. I'll close the issue.
