### ISSUE TITLE
422 (Unprocesable Entity)

### ISSUE THREAD

**Issue by abelnexus** [jesusantguerrero/sunday#88]
![Capture](https://user-images.githubusercontent.com/34687414/127719697-cbdaddcc-209c-4a08-8b44-c9ac7449885f.PNG)

why does it give me that error?

**Comment by jesusantguerrero** [comment]
Did you run the seeders?
`php artisan db:seed`

**Comment by abelnexus** [comment]
Yes, I followed all the steps, but when I use npm run watch it shows me the phpmyadmin dashboard, that's why I use php artisan serve

**Comment by jesusantguerrero** [comment]
It's weird I did a test before and after running following the steps and it doesn't happen to me. Can you open the network tab on the console to see if the message it's more clear?

**Comment by abelnexus** [comment]
![Capture](https://user-images.githubusercontent.com/34687414/127744190-8b3e1fd6-d1ea-452f-8ecf-c524ec93e616.PNG)
this is the show in console, and if I click:
![Capture2](https://user-images.githubusercontent.com/34687414/127744251-ef408167-3905-463b-a921-411d90fde91f.PNG)

**Comment by jesusantguerrero** [comment]
But I mean the `network` tab It is after `source`  the next one.
![image](https://user-images.githubusercontent.com/17421742/127744457-bff62398-faff-4813-8e3e-8fe1fc538963.png)

**Comment by abelnexus** [comment]
![Capture](https://user-images.githubusercontent.com/34687414/127744490-8e4680ad-abb6-4d16-892f-ff8e14e9cfb8.PNG)

**Comment by abelnexus** [comment]
I already saw what it is about, the password +8 character accepted
![Capture](https://user-images.githubusercontent.com/34687414/127744684-7df6ab90-7e0d-4394-99e1-91fb4e897702.PNG)

**Comment by jesusantguerrero** [comment]
Oh, I missed putting that validation message in the frontend. Thanks for letting me know.
